package com.clinicpatientqueueexample.doctorsoffice;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot @AutoGenerated @SuppressWarnings("serial") public class DoctorsOfficeDesign
    extends VerticalLayout {
    protected Label doctorsOfficeNameLabel;
    protected Button logoutButton;
    protected Label doctorNameLabel;
    protected Button callInButton;
    protected Grid<com.clinicpatientqueueexample.patients.Registration> registeredPatientsGrid;

    public DoctorsOfficeDesign() {
        Design.read(this);
    }
}
