package com.clinicpatientqueueexample.infoscreen;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Grid;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot @AutoGenerated @SuppressWarnings("serial") public class InfoscreenDesign extends VerticalLayout {
    protected Grid<com.clinicpatientqueueexample.patients.Registration> calledInPatientsGrid;

    public InfoscreenDesign() {
        Design.read(this);
    }
}
